import { v4 as uuidv4 } from 'uuid';

// Mock Users Data
export const mockUsers = [
  {
    id: 'user-001',
    name: 'ADMIN USER',
    email: 'admin@cyberaudit.com',
    role: 'ADMIN',
    company: 'CyberAudit',
    status: 'ACTIVE',
    lastLogin: '2024-04-08T10:30:00Z',
    mfaEnabled: true,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-002',
    name: 'CHEF MANAGER',
    email: 'chef@cyberaudit.com',
    role: 'CHEF',
    company: 'KSI Security',
    status: 'ACTIVE',
    lastLogin: '2024-04-08T09:15:00Z',
    mfaEnabled: false,
    createdAt: '2024-01-05T00:00:00Z',
  },
  {
    id: 'user-003',
    name: 'AUDITOR ONE',
    email: 'auditor1@cyberaudit.com',
    role: 'AUDITOR',
    company: 'SecureX',
    status: 'ACTIVE',
    lastLogin: '2024-04-08T08:45:00Z',
    mfaEnabled: true,
    createdAt: '2024-01-10T00:00:00Z',
  },
  {
    id: 'user-004',
    name: 'CLIENT USER',
    email: 'client@company.com',
    role: 'CLIENT',
    company: 'TechCorp',
    status: 'ACTIVE',
    lastLogin: '2024-04-07T15:30:00Z',
    mfaEnabled: false,
    createdAt: '2024-02-01T00:00:00Z',
  },
];

// Mock Vulnerabilities Data
export const mockVulnerabilities = [
  {
    id: 'vuln-001',
    title: 'SQL Injection in Login Form',
    severity: 'CRITICAL',
    cveId: 'CVE-2024-12345',
    description: 'SQL injection vulnerability found in user authentication form',
    affectedHosts: ['host-001', 'host-002'],
    discoveredDate: '2024-04-05T12:00:00Z',
    status: 'OPEN',
    priority: 95,
    remediationTime: '2 hours',
    complexity: 'High',
  },
  {
    id: 'vuln-002',
    title: 'Weak SSL Configuration',
    severity: 'HIGH',
    cveId: 'CVE-2024-54321',
    description: 'Server uses outdated SSL/TLS protocols',
    affectedHosts: ['host-001', 'host-003'],
    discoveredDate: '2024-04-06T10:30:00Z',
    status: 'IN_PROGRESS',
    priority: 78,
    remediationTime: '1 day',
    complexity: 'Medium',
  },
  {
    id: 'vuln-003',
    title: 'Missing CSRF Protection',
    severity: 'MEDIUM',
    cveId: 'CVE-2024-99999',
    description: 'Cross-site request forgery vulnerability',
    affectedHosts: ['host-002'],
    discoveredDate: '2024-04-07T08:00:00Z',
    status: 'OPEN',
    priority: 45,
    remediationTime: '4 hours',
    complexity: 'Low',
  },
  {
    id: 'vuln-004',
    title: 'Outdated Dependencies',
    severity: 'MEDIUM',
    cveId: 'CVE-2024-88888',
    description: 'Application uses outdated and vulnerable dependencies',
    affectedHosts: ['host-003', 'host-004'],
    discoveredDate: '2024-04-04T14:20:00Z',
    status: 'RESOLVED',
    priority: 52,
    remediationTime: '3 hours',
    complexity: 'Low',
  },
  {
    id: 'vuln-005',
    title: 'Weak Password Policy',
    severity: 'MEDIUM',
    cveId: 'CVE-2024-77777',
    description: 'Weak password requirements allow easily guessable credentials',
    affectedHosts: ['host-001'],
    discoveredDate: '2024-04-03T11:00:00Z',
    status: 'OPEN',
    priority: 65,
    remediationTime: '1 hour',
    complexity: 'Low',
  },
];

// Mock Hosts Data
export const mockHosts = [
  {
    id: 'host-001',
    name: 'Web Server 1',
    ipAddress: '192.168.1.10',
    hostname: 'web1.example.com',
    os: 'Ubuntu 22.04 LTS',
    status: 'ONLINE',
    lastScanned: '2024-04-08T09:00:00Z',
    vulnerabilityCount: 3,
  },
  {
    id: 'host-002',
    name: 'Database Server',
    ipAddress: '192.168.1.20',
    hostname: 'db1.example.com',
    os: 'CentOS 8',
    status: 'ONLINE',
    lastScanned: '2024-04-08T08:30:00Z',
    vulnerabilityCount: 2,
  },
  {
    id: 'host-003',
    name: 'API Server',
    ipAddress: '192.168.1.30',
    hostname: 'api.example.com',
    os: 'Ubuntu 20.04 LTS',
    status: 'ONLINE',
    lastScanned: '2024-04-07T14:15:00Z',
    vulnerabilityCount: 2,
  },
  {
    id: 'host-004',
    name: 'DNS Server',
    ipAddress: '192.168.1.40',
    hostname: 'dns1.example.com',
    os: 'Windows Server 2019',
    status: 'OFFLINE',
    lastScanned: '2024-04-06T10:00:00Z',
    vulnerabilityCount: 1,
  },
];

// Mock Reports Data
export const mockReports = [
  {
    id: 'report-001',
    title: 'Q1 2024 Security Audit - TechCorp',
    organization: 'TechCorp',
    clientId: 'user-004',
    auditorId: 'user-003',
    createdDate: '2024-04-01T10:00:00Z',
    completedDate: '2024-04-08T15:30:00Z',
    status: 'COMPLETED',
    grade: 'C+',
    totalVulnerabilities: 12,
    criticalCount: 1,
    highCount: 3,
    mediumCount: 5,
    lowCount: 3,
    executiveSummary: 'Organization has moderate security posture with critical findings requiring immediate attention.',
  },
  {
    id: 'report-002',
    title: 'Vulnerability Assessment - SecureX',
    organization: 'SecureX',
    clientId: 'user-004',
    auditorId: 'user-003',
    createdDate: '2024-03-15T09:00:00Z',
    completedDate: null,
    status: 'IN_PROGRESS',
    grade: null,
    totalVulnerabilities: 8,
    criticalCount: 0,
    highCount: 2,
    mediumCount: 4,
    lowCount: 2,
    executiveSummary: null,
  },
  {
    id: 'report-003',
    title: 'Penetration Test Report - Enterprise Corp',
    organization: 'Enterprise Corp',
    clientId: 'user-004',
    auditorId: 'user-003',
    createdDate: '2024-02-20T11:00:00Z',
    completedDate: '2024-03-20T16:45:00Z',
    status: 'COMPLETED',
    grade: 'B',
    totalVulnerabilities: 5,
    criticalCount: 0,
    highCount: 1,
    mediumCount: 3,
    lowCount: 1,
    executiveSummary: 'Strong security baseline with minor areas for improvement.',
  },
];

// Mock Organizations Data
export const mockOrganizations = [
  {
    id: 'org-001',
    name: 'TechCorp',
    industry: 'Technology',
    size: 'LARGE',
    country: 'France',
    website: 'techcorp.fr',
    createdDate: '2024-01-15T00:00:00Z',
    perimeters: ['perimeter-001'],
  },
  {
    id: 'org-002',
    name: 'SecureX',
    industry: 'Cybersecurity',
    size: 'MEDIUM',
    country: 'France',
    website: 'securex.fr',
    createdDate: '2024-02-01T00:00:00Z',
    perimeters: ['perimeter-002', 'perimeter-003'],
  },
  {
    id: 'org-003',
    name: 'Finance Plus',
    industry: 'Finance',
    size: 'LARGE',
    country: 'France',
    website: 'financeplus.fr',
    createdDate: '2024-01-20T00:00:00Z',
    perimeters: ['perimeter-004'],
  },
];

// Mock Notifications Data
export const mockNotifications = [
  {
    id: 'notif-001',
    type: 'CRITICAL_VULN_FOUND',
    title: 'Critical Vulnerability Detected',
    message: 'SQL Injection found in production server',
    severity: 'CRITICAL',
    read: false,
    createdAt: '2024-04-08T14:30:00Z',
    userId: 'user-001',
  },
  {
    id: 'notif-002',
    type: 'REPORT_COMPLETED',
    title: 'Report Generation Complete',
    message: 'Report "Q1 2024 Security Audit" is ready for download',
    severity: 'INFO',
    read: false,
    createdAt: '2024-04-08T13:45:00Z',
    userId: 'user-003',
  },
  {
    id: 'notif-003',
    type: 'SCAN_FINISHED',
    title: 'Security Scan Completed',
    message: '5 new vulnerabilities found on Web Server 1',
    severity: 'HIGH',
    read: true,
    createdAt: '2024-04-08T10:00:00Z',
    userId: 'user-001',
  },
  {
    id: 'notif-004',
    type: 'USER_REGISTERED',
    title: 'New User Registration',
    message: 'New user "John Doe" registered as AUDITOR',
    severity: 'INFO',
    read: true,
    createdAt: '2024-04-08T09:30:00Z',
    userId: 'user-001',
  },
];

// Mock Scanner Configuration
export const mockScanners = [
  {
    id: 'scanner-001',
    name: 'OpenVAS Scanner 1',
    type: 'OpenVAS',
    endpoint: '192.168.1.50:9392',
    status: 'Online',
    version: '24.1.0',
    lastHealthCheck: '2024-04-08T10:00:00Z',
    load: 45,
  },
  {
    id: 'scanner-002',
    name: 'Nessus Scanner 1',
    type: 'Nessus',
    endpoint: '192.168.1.51:8834',
    status: 'Online',
    version: '10.5.0',
    lastHealthCheck: '2024-04-08T10:05:00Z',
    load: 60,
  },
  {
    id: 'scanner-003',
    name: 'OWASP ZAP Scanner',
    type: 'OWASP-ZAP',
    endpoint: '192.168.1.52:8080',
    status: 'Offline',
    version: '2.14.0',
    lastHealthCheck: '2024-04-07T15:00:00Z',
    load: 0,
  },
];

// Mock Scaling Configuration
export const mockScalingConfig = {
  id: 'scaling-001',
  autoscalingEnabled: true,
  minInstances: 2,
  maxInstances: 10,
  cpuThreshold: 70,
  memoryThreshold: 80,
  scaleUpCooldown: 300,
  scaleDownCooldown: 900,
};

// Mock Role Requests (for user registration)
export const mockRoleRequests = [
  {
    id: 'role-req-001',
    name: 'John Doe',
    email: 'john.doe@example.com',
    requestedRole: 'AUDITOR',
    company: 'SecureX',
    createdAt: '2024-04-08T08:00:00Z',
    status: 'PENDING',
  },
  {
    id: 'role-req-002',
    name: 'Jane Smith',
    email: 'jane.smith@company.com',
    requestedRole: 'CLIENT',
    company: 'TechCorp',
    createdAt: '2024-04-07T14:30:00Z',
    status: 'PENDING',
  },
];

// Mock CVE Library
export const mockCVELibrary = [
  {
    id: 'cve-01',
    cveId: 'CVE-2024-12345',
    title: 'SQL Injection Vulnerability',
    description: 'Critical SQL injection vulnerability in web applications',
    severity: 'CRITICAL',
    cvssScore: 9.8,
    publishedDate: '2024-03-01T00:00:00Z',
    affectedSoftware: ['Apache', 'Nginx'],
    remediationAdvice: 'Update to latest version and use parameterized queries',
  },
  {
    id: 'cve-02',
    cveId: 'CVE-2024-54321',
    title: 'SSL/TLS Configuration Issue',
    description: 'Weak SSL/TLS configuration allowing downgrade attacks',
    severity: 'HIGH',
    cvssScore: 7.5,
    publishedDate: '2024-02-15T00:00:00Z',
    affectedSoftware: ['OpenSSL', 'LibreSSL'],
    remediationAdvice: 'Update SSL/TLS configuration and disable weak protocols',
  },
  {
    id: 'cve-03',
    cveId: 'CVE-2024-99999',
    title: 'CSRF Protection Missing',
    description: 'Cross-site request forgery protection not implemented',
    severity: 'MEDIUM',
    cvssScore: 6.5,
    publishedDate: '2024-01-20T00:00:00Z',
    affectedSoftware: ['Custom Web App'],
    remediationAdvice: 'Implement CSRF tokens in all state-changing operations',
  },
];

// Export all mock data
export const mockData = {
  users: mockUsers,
  vulnerabilities: mockVulnerabilities,
  hosts: mockHosts,
  reports: mockReports,
  organizations: mockOrganizations,
  notifications: mockNotifications,
  scanners: mockScanners,
  scalingConfig: mockScalingConfig,
  roleRequests: mockRoleRequests,
  cveLibrary: mockCVELibrary,
};

export default mockData;
